{
 "title": "TEST",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Airflow" }
  ]
 },
 "panels": [
  { "title": "Airflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Airflow dags",
   "type": "nodeGraph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "target": "dags", "type": "table" }
   ]
  },
  {
   "title": "Latest state change (tasks)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (delta(airflow_task_status[$__interval]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "All tasks fails",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_id) (airflow_task_fail_count)",
     "legendFormat": "{{ task_id }}"
    }
   ]
  },
  {
   "title": "Scheduler delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_dag_scheduler_delay" }
   ]
  },
  {
   "title": "Longest tasks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum(airflow_successful_task_duration) by (task_id)))",
     "legendFormat": "{{ task_id }}"
    }
   ]
  },
  {
   "title": "Last DAG runs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (airflow_last_dag_run)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Queued tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_num_queued_tasks" }
   ]
  }
 ]
}